# Mod
mod_id = inventoryessentials
mod_name=Inventory Essentials
mod_author = BlayTheNinth
credits = BlayTheNinth
description=Basic inventory tweaks. Lightweight and compatible.
version = 26.1.2.4
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/inventory-essentials
sources=https://github.com/TwelveIterations/InventoryEssentials
issues=https://github.com/TwelveIterations/InventoryEssentials/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 368825
curseforge_environments = Client,Server
modrinth_project_id = Boon8xwi
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url =
include_fabric=true
include_neoforge=true
include_forge=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
